include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - '**/*.g.dart'
    - '**/*.mocks.dart'
    - '**/*.config.dart'
    - '**/firebase_options.dart'
    - '**/color_schemes.dart'

linter:
  rules:
    always_declare_return_types: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_void_async: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    empty_statements: true
    implementation_imports: true
    library_names: true
    overridden_fields: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_foreach: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_this: true
    depend_on_referenced_packages: false

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    halstead-volume: 150
    lines-of-code: 100
    maintainability-index: 50
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 4
    source-lines-of-code: 50
    technical-debt:
      threshold: 1
      todo-cost: 161
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322
      deprecated-annotations-cost: 37
      file-nullsafety-migration-cost: 41
      unit-type: "EUR"
    weight-of-class: 0.33
  rules:
    - prefer-static-class: false
    - avoid-non-ascii-symbols: false
    - avoid-ignoring-return-values: false
    - arguments-ordering:
        child-last: true
    - avoid-returning-widgets:
        ignored-names:
          - testFunction
    - no-equal-arguments: false
    - avoid-late-keyword: false
    - prefer-correct-identifier-length:
        exceptions: [ 'id' ]
        max-identifier-length: 30
        min-identifier-length: 3
    - member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - public-methods
          - private-methods
          - public-getters
          - private-getters
          - public-setters
          - private-setters
        widgets-order:
          - constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
          - build-method
    - format-comment:
        only-doc-comments: true
