name: locami

packages:
  - '*'
  - _modules/*

ide:
  intellij: false

scripts:
  postclean: melos exec --flutter --concurrency=1 -- "flutter clean" && find . -type f -name "*.iml" -exec rm -f {} \;

  generate: melos exec --concurrency=1 -- "flutter pub run build_runner build --delete-conflicting-outputs"

  generate_assets: melos exec --flutter --concurrency=1 --fail-fast -- "flutter pub run assets_gen build"

  upgrade_dependencies: melos exec --concurrency=1 -- "flutter pub upgrade --major-versions"

  generate_locale:
    run: |
      melos exec --flutter --concurrency=1 --fail-fast -- \
      "flutter pub run easy_localization:generate -f keys -S "assets/translations" -O "lib/translations" -o "translations_keys.g.dart" --skip-unnecessary-keys"
    select-package:
      depends-on:
        - "easy_localization"

  dev_dependencies: |
    melos exec --concurrency=1 -- "flutter pub add \
    --dev \
    build_runner \
    build_verify \
    go_router_builder \
    injectable_generator \
    dart_code_metrics \
    assets_gen \
    "
