name: locami
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  reactive_forms: ^14.2.0
  firebase_core: ^2.8.0
  cloud_functions: ^4.0.13
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  adaptive_dialog: ^1.8.2
  go_router: ^6.2.0
  easy_localization: ^3.0.1
  responsive_sizer: ^3.1.1
  flutter_svg: ^2.0.4
  json_annotation: ^4.8.0
  google_fonts: ^4.0.3

dependency_overrides:
  intl:  ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  go_router_builder: ^1.1.7
  injectable_generator: ^2.1.4
  dart_code_metrics: ^5.6.0
  assets_gen: ^1.5.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - .env/
    - assets/images/
    - assets/translations/

assets_gen:
  output: core/theme/assets.g.dart
  code_style: lowerCamelCase
