name: locami
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  reactive_forms: ^14.1.0
  firebase_core: ^2.4.1
  cloud_functions: ^4.0.7
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  adaptive_dialog: ^1.8.1+1
  go_router: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
